language: crystal

sudo: required
services:
  - docker

matrix:
  include:
    - install: # Ubuntu 20.04 (Xenial)
      - docker build . -f ci/Dockerfile.ubuntu -t bindgen-test
    - install: # Debian 11.0 (Bullseye)
      - docker build . -f ci/Dockerfile.debian -t bindgen-test
    - install: # ArchLinux (Rolling)
      - docker build . -f ci/Dockerfile.archlinux -t bindgen-test

script:
  - docker run --rm bindgen-test ci/run.sh
