# Dockerfile for bindgen, used for automated testing on travis-ci.org

FROM debian:bullseye
ARG DISTRIB_CODENAME=bullseye

COPY . /bindgen

RUN /bindgen/ci/install_debian.sh

WORKDIR /bindgen/clang
RUN cmake . && make
WORKDIR /bindgen
