# Dockerfile for bindgen, used for automated testing on travis-ci.org

ARG DISTRIB_CODENAME=focal
FROM ubuntu:${DISTRIB_CODENAME}

COPY . /bindgen

RUN /bindgen/ci/install_debian.sh

WORKDIR /bindgen/clang
RUN cmake . && make
WORKDIR /bindgen
