# Dockerfile for bindgen, used for automated testing on travis-ci.org

FROM debian:stretch
ARG CLANG_VERSION=10
ARG DISTRIB_CODENAME=stretch

COPY . /bindgen

RUN /bindgen/ci/install_debian.sh

WORKDIR /bindgen/clang
RUN cmake . && make
WORKDIR /bindgen
