# Dockerfile for bindgen, used for automated testing on travis-ci.org

FROM ubuntu:focal
ARG DISTRIB_CODENAME=focal

COPY . /bindgen

RUN /bindgen/ci/install_debian.sh

WORKDIR /bindgen/clang
RUN cmake . && make
WORKDIR /bindgen
