# Dockerfile for bindgen, used for automated testing on travis-ci.org

FROM archlinux:base-devel

COPY . /bindgen

RUN pacman -Syu --noconfirm cmake llvm clang crystal shards libyaml

ENV BINDGEN_DYNAMIC=1

WORKDIR /bindgen/clang
RUN cmake . && make
WORKDIR /bindgen
