name: Test

on:
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * *' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ci/llvm.dockerfile --tag bindgen-test:$(date +%s)
