name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:

  CI:
    strategy:
      fail-fast: false
      matrix:
        llvm_version: [11, 12, 13, 14]
        channel: [stable, nightly]

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: >
        docker build . --file ci/llvm.dockerfile
        --tag bindgen-test:${{ matrix.llvm_version }}-${{ matrix.channel }}
        --build-arg LLVM_VERSION=${{ matrix.llvm_version }}
        --build-arg CRYSTAL_CHANNEL=${{ matrix.channel }}

    - name: Run test
      run: docker run --rm bindgen-test:${{ matrix.llvm_version }}-${{ matrix.channel }} ci/run.sh
