name: Test

on:
  push:
  pull_request:

jobs:

  CI:
    strategy:
      fail-fast: false
      matrix:
        llvm_version: [11, 12, 13, 14]
        crystal_version: [1.1, 1.2, 1.3]

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: >
        docker build . --file ci/llvm.dockerfile
        --tag bindgen-test:${{ matrix.llvm_version }}-${{ matrix.crystal_version }}
        --build-arg LLVM_VERSION=${{ matrix.llvm_version }}
        --build-arg CRYSTAL_VERSION=${{ matrix.crystal_version }}

    - name: Run test
      run: docker run --rm bindgen-test:${{ matrix.llvm_version }}-${{ matrix.crystal_version }} ci/run.sh
